### ISSUE TITLE
Production build not working

### ISSUE THREAD

**Issue by kartiklad** [Life-Letters/universal-react-redux#1]
npm run prod:build throws the following error

> /Users/kartiklad/Work/universal-react-redux/node_modules/babel-cli/lib/_babel-node.js:94
  code = code.trim();
              ^
> TypeError: code.trim is not a function
>     at _eval (/Users/kartiklad/Work/universal-react-redux/node_modules/babel-cli/lib/_babel-node.js:94:15)
>     at Object.<anonymous> (/Users/kartiklad/Work/universal-react-redux/node_modules/babel-cli/lib/_babel-node.js:123:16)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Function.Module.runMain (module.js:441:10)
>     at startup (node.js:139:18)
>     at node.js:974:3

**Comment by kartiklad** [comment]
fixed with this commit -> [aff833261e0058fe7825c62e34f26b7e70b2fde8](https://github.com/Life-Letters/universal-react-redux/commit/aff833261e0058fe7825c62e34f26b7e70b2fde8)
